#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def collect_chapters(chapter_dir: Path) -> list[Path]:
    return sorted(chapter_dir.glob("chapter-*.md"))


def assemble_markdown(chapters: list[Path]) -> str:
    output: list[str] = []
    output.append("# Screenplay Draft\n")

    for chapter in chapters:
        content = chapter.read_text(encoding="utf-8")
        output.append("\n---\n")
        output.append(f"\n## Source: {chapter.name}\n")
        output.append(content)

    return "\n".join(output)


def clean_fountain_line(line: str) -> str:
    line = re.sub(r"^#+\s*", "", line).strip()
    line = line.replace("**", "")
    line = line.replace("__", "")
    return line


def assemble_fountain(chapters: list[Path]) -> str:
    output: list[str] = []
    output.append("Title: Screenplay Draft")
    output.append("Credit: Generated by EchoMedia Content Engine")
    output.append("")

    for chapter in chapters:
        title = chapter.stem.replace("-", " ").title()
        output.append(f"# {title}")
        output.append(f"INT. {title.upper()} - DAY")
        output.append("")

        for line in chapter.read_text(encoding="utf-8").splitlines():
            cleaned = clean_fountain_line(line)
            if not cleaned:
                output.append("")
                continue
            if cleaned.startswith("-"):
                continue
            output.append(cleaned)

        output.append("")

    return "\n".join(output).rstrip() + "\n"


def build_scene_cards(chapters: list[Path]) -> list[dict]:
    scenes: list[dict] = []

    for index, chapter in enumerate(chapters, start=1):
        title = chapter.stem.replace("-", " ").title()
        content = chapter.read_text(encoding="utf-8")
        word_count = len(re.findall(r"\b\w+\b", content))

        scenes.append({
            "scene_id": f"SCN-{index:03d}",
            "source_chapter": chapter.name,
            "title": title,
            "estimated_words": word_count,
            "status": "draft",
            "story_objective": "TODO",
            "emotional_objective": "TODO",
            "continuity_notes": [],
            "adaptation_notes": [],
        })

    return scenes


def write_scene_cards(project_root: Path, scenes: list[dict]) -> None:
    scene_dir = project_root / "screenplay/scenes"
    scene_dir.mkdir(parents=True, exist_ok=True)

    for scene in scenes:
        scene_path = scene_dir / f"{scene['scene_id'].lower()}.json"
        scene_path.write_text(json.dumps(scene, indent=2) + "\n", encoding="utf-8")

    index_path = scene_dir / "scene-index.json"
    index_path.write_text(json.dumps({"scene_count": len(scenes), "scenes": scenes}, indent=2) + "\n", encoding="utf-8")


def write_outputs(project_root: Path, markdown: str, fountain: str, chapter_count: int, scene_count: int) -> None:
    export_dir = project_root / "screenplay/exports"
    export_dir.mkdir(parents=True, exist_ok=True)

    markdown_path = export_dir / "screenplay-draft.md"
    markdown_path.write_text(markdown, encoding="utf-8")

    fountain_path = export_dir / "screenplay-draft.fountain"
    fountain_path.write_text(fountain, encoding="utf-8")

    report = {
        "chapter_count": chapter_count,
        "scene_count": scene_count,
        "status": "assembled",
        "markdown_output": str(markdown_path),
        "fountain_output": str(fountain_path),
        "scene_index": str(project_root / "screenplay/scenes/scene-index.json"),
    }

    report_path = export_dir / "screenplay-assembly-report.json"
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("project_root", type=Path)
    args = parser.parse_args()

    chapter_dir = args.project_root / "manuscript/chapters"
    chapters = collect_chapters(chapter_dir)

    markdown = assemble_markdown(chapters)
    fountain = assemble_fountain(chapters)
    scenes = build_scene_cards(chapters)

    write_scene_cards(args.project_root, scenes)
    write_outputs(args.project_root, markdown, fountain, len(chapters), len(scenes))

    print(f"Assembled screenplay draft from {len(chapters)} chapter(s).")
    print(f"Generated {len(scenes)} scene card(s).")
    print("Wrote Markdown and Fountain exports.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
