#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

WORDS_PER_SCREEN_MINUTE = 130
MIN_SCENE_SECONDS = 30
TRAILER_TERMS = {
    "reveal",
    "secret",
    "choice",
    "betrayal",
    "danger",
    "chase",
    "fight",
    "kiss",
    "death",
    "truth",
    "escape",
    "warning",
    "fire",
    "blood",
    "storm",
    "silence",
    "door",
    "last",
    "first",
    "final",
}


def collect_chapters(chapter_dir: Path) -> list[Path]:
    return sorted(chapter_dir.glob("chapter-*.md"))


def assemble_markdown(chapters: list[Path]) -> str:
    output: list[str] = []
    output.append("# Screenplay Draft\n")

    for chapter in chapters:
        content = chapter.read_text(encoding="utf-8")
        output.append("\n---\n")
        output.append(f"\n## Source: {chapter.name}\n")
        output.append(content)

    return "\n".join(output)


def clean_fountain_line(line: str) -> str:
    line = re.sub(r"^#+\s*", "", line).strip()
    line = line.replace("**", "")
    line = line.replace("__", "")
    return line


def assemble_fountain(chapters: list[Path]) -> str:
    output: list[str] = []
    output.append("Title: Screenplay Draft")
    output.append("Credit: Generated by EchoMedia Content Engine")
    output.append("")

    for chapter in chapters:
        title = chapter.stem.replace("-", " ").title()
        output.append(f"# {title}")
        output.append(f"INT. {title.upper()} - DAY")
        output.append("")

        for line in chapter.read_text(encoding="utf-8").splitlines():
            cleaned = clean_fountain_line(line)
            if not cleaned:
                output.append("")
                continue
            if cleaned.startswith("-"):
                continue
            output.append(cleaned)

        output.append("")

    return "\n".join(output).rstrip() + "\n"


def estimate_runtime_seconds(word_count: int) -> int:
    estimated = int((word_count / WORDS_PER_SCREEN_MINUTE) * 60)
    return max(MIN_SCENE_SECONDS, estimated)


def format_runtime(seconds: int) -> str:
    minutes = seconds // 60
    remaining_seconds = seconds % 60
    return f"{minutes:02d}:{remaining_seconds:02d}"


def score_trailer_suitability(content: str, runtime_seconds: int) -> dict:
    tokens = set(re.findall(r"\b[a-zA-Z][a-zA-Z0-9_-]*\b", content.lower()))
    matched_terms = sorted(tokens & TRAILER_TERMS)
    term_score = min(60, len(matched_terms) * 8)
    runtime_score = 20 if 30 <= runtime_seconds <= 180 else 10
    density_score = 20 if len(tokens) >= 80 else 10
    score = min(100, term_score + runtime_score + density_score)

    if score >= 70:
        status = "strong"
    elif score >= 40:
        status = "candidate"
    else:
        status = "low"

    return {
        "score": score,
        "status": status,
        "matched_terms": matched_terms,
    }


def build_scene_cards(chapters: list[Path]) -> list[dict]:
    scenes: list[dict] = []

    for index, chapter in enumerate(chapters, start=1):
        title = chapter.stem.replace("-", " ").title()
        content = chapter.read_text(encoding="utf-8")
        word_count = len(re.findall(r"\b\w+\b", content))
        runtime_seconds = estimate_runtime_seconds(word_count)
        trailer = score_trailer_suitability(content, runtime_seconds)

        scenes.append({
            "scene_id": f"SCN-{index:03d}",
            "source_chapter": chapter.name,
            "title": title,
            "estimated_words": word_count,
            "estimated_runtime_seconds": runtime_seconds,
            "estimated_runtime": format_runtime(runtime_seconds),
            "trailer_suitability": trailer,
            "status": "draft",
            "story_objective": "TODO",
            "emotional_objective": "TODO",
            "continuity_notes": [],
            "adaptation_notes": [],
        })

    return scenes


def build_runtime_report(scenes: list[dict]) -> dict:
    total_seconds = sum(scene["estimated_runtime_seconds"] for scene in scenes)
    return {
        "scene_count": len(scenes),
        "total_runtime_seconds": total_seconds,
        "total_runtime": format_runtime(total_seconds),
        "average_scene_seconds": int(total_seconds / len(scenes)) if scenes else 0,
        "average_scene_runtime": format_runtime(int(total_seconds / len(scenes))) if scenes else "00:00",
        "scenes": [
            {
                "scene_id": scene["scene_id"],
                "title": scene["title"],
                "estimated_runtime": scene["estimated_runtime"],
            }
            for scene in scenes
        ],
    }


def build_trailer_report(scenes: list[dict]) -> dict:
    ranked = sorted(
        scenes,
        key=lambda scene: scene["trailer_suitability"]["score"],
        reverse=True,
    )
    return {
        "scene_count": len(scenes),
        "recommended_scenes": [
            {
                "scene_id": scene["scene_id"],
                "title": scene["title"],
                "score": scene["trailer_suitability"]["score"],
                "status": scene["trailer_suitability"]["status"],
                "matched_terms": scene["trailer_suitability"]["matched_terms"],
            }
            for scene in ranked[:10]
        ],
    }


def write_scene_cards(project_root: Path, scenes: list[dict]) -> None:
    scene_dir = project_root / "screenplay/scenes"
    scene_dir.mkdir(parents=True, exist_ok=True)

    for scene in scenes:
        scene_path = scene_dir / f"{scene['scene_id'].lower()}.json"
        scene_path.write_text(json.dumps(scene, indent=2) + "\n", encoding="utf-8")

    index_path = scene_dir / "scene-index.json"
    index_path.write_text(json.dumps({"scene_count": len(scenes), "scenes": scenes}, indent=2) + "\n", encoding="utf-8")


def write_outputs(project_root: Path, markdown: str, fountain: str, chapter_count: int, scenes: list[dict]) -> None:
    export_dir = project_root / "screenplay/exports"
    export_dir.mkdir(parents=True, exist_ok=True)

    markdown_path = export_dir / "screenplay-draft.md"
    markdown_path.write_text(markdown, encoding="utf-8")

    fountain_path = export_dir / "screenplay-draft.fountain"
    fountain_path.write_text(fountain, encoding="utf-8")

    runtime_report_path = export_dir / "runtime-report.json"
    runtime_report_path.write_text(json.dumps(build_runtime_report(scenes), indent=2) + "\n", encoding="utf-8")

    trailer_report_path = export_dir / "trailer-suitability-report.json"
    trailer_report_path.write_text(json.dumps(build_trailer_report(scenes), indent=2) + "\n", encoding="utf-8")

    report = {
        "chapter_count": chapter_count,
        "scene_count": len(scenes),
        "status": "assembled",
        "markdown_output": str(markdown_path),
        "fountain_output": str(fountain_path),
        "scene_index": str(project_root / "screenplay/scenes/scene-index.json"),
        "runtime_report": str(runtime_report_path),
        "trailer_suitability_report": str(trailer_report_path),
    }

    report_path = export_dir / "screenplay-assembly-report.json"
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("project_root", type=Path)
    args = parser.parse_args()

    chapter_dir = args.project_root / "manuscript/chapters"
    chapters = collect_chapters(chapter_dir)

    markdown = assemble_markdown(chapters)
    fountain = assemble_fountain(chapters)
    scenes = build_scene_cards(chapters)

    write_scene_cards(args.project_root, scenes)
    write_outputs(args.project_root, markdown, fountain, len(chapters), scenes)

    runtime = build_runtime_report(scenes)["total_runtime"]

    print(f"Assembled screenplay draft from {len(chapters)} chapter(s).")
    print(f"Generated {len(scenes)} scene card(s).")
    print(f"Estimated runtime: {runtime}")
    print("Wrote Markdown, Fountain, runtime, and trailer suitability exports.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
