#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def collect_chapters(chapter_dir: Path) -> list[Path]:
    return sorted(chapter_dir.glob("chapter-*.md"))


def assemble_markdown(chapters: list[Path]) -> str:
    output: list[str] = []
    output.append("# Screenplay Draft\n")

    for chapter in chapters:
        content = chapter.read_text(encoding="utf-8")
        output.append("\n---\n")
        output.append(f"\n## Source: {chapter.name}\n")
        output.append(content)

    return "\n".join(output)


def clean_fountain_line(line: str) -> str:
    line = re.sub(r"^#+\s*", "", line).strip()
    line = line.replace("**", "")
    line = line.replace("__", "")
    return line


def assemble_fountain(chapters: list[Path]) -> str:
    output: list[str] = []
    output.append("Title: Screenplay Draft")
    output.append("Credit: Generated by EchoMedia Content Engine")
    output.append("")

    for chapter in chapters:
        title = chapter.stem.replace("-", " ").title()
        output.append(f"# {title}")
        output.append(f"INT. {title.upper()} - DAY")
        output.append("")

        for line in chapter.read_text(encoding="utf-8").splitlines():
            cleaned = clean_fountain_line(line)
            if not cleaned:
                output.append("")
                continue
            if cleaned.startswith("-"):
                continue
            output.append(cleaned)

        output.append("")

    return "\n".join(output).rstrip() + "\n"


def write_outputs(project_root: Path, markdown: str, fountain: str, chapter_count: int) -> None:
    export_dir = project_root / "screenplay/exports"
    export_dir.mkdir(parents=True, exist_ok=True)

    markdown_path = export_dir / "screenplay-draft.md"
    markdown_path.write_text(markdown, encoding="utf-8")

    fountain_path = export_dir / "screenplay-draft.fountain"
    fountain_path.write_text(fountain, encoding="utf-8")

    report = {
        "chapter_count": chapter_count,
        "status": "assembled",
        "markdown_output": str(markdown_path),
        "fountain_output": str(fountain_path),
    }

    report_path = export_dir / "screenplay-assembly-report.json"
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("project_root", type=Path)
    args = parser.parse_args()

    chapter_dir = args.project_root / "manuscript/chapters"
    chapters = collect_chapters(chapter_dir)

    markdown = assemble_markdown(chapters)
    fountain = assemble_fountain(chapters)

    write_outputs(args.project_root, markdown, fountain, len(chapters))

    print(f"Assembled screenplay draft from {len(chapters)} chapter(s).")
    print("Wrote Markdown and Fountain exports.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
